FROM ubuntu:24.04

ENV DEBIAN_FRONTEND=noninteractive

# -------------------------------
# Install base tools and Python
# -------------------------------
RUN apt update && apt install -y \
    python3 python3-pip python3-venv \
    openjdk-11-jdk \
    openssh-server \
    curl wget git nano sudo \
    && apt clean && rm -rf /var/lib/apt/lists/*

# -------------------------------
# Setup SSH access
# -------------------------------
RUN mkdir /var/run/sshd \
    && echo 'root:root' | chpasswd \
    && sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

# -------------------------------
# Install Apache Spark
# -------------------------------
ENV SPARK_VERSION=3.4.0
ENV HADOOP_VERSION=3

RUN wget https://archive.apache.org/dist/spark/spark-${SPARK_VERSION}/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz \
    && tar -xzf spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz -C /opt \
    && ln -s /opt/spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION} /opt/spark \
    && rm spark-${SPARK_VERSION}-bin-hadoop${HADOOP_VERSION}.tgz

ENV SPARK_HOME=/opt/spark
ENV PATH=$PATH:$SPARK_HOME/bin

# -------------------------------
# Default command: SSH daemon
# -------------------------------
EXPOSE 22 8888 4040 4041 4042
CMD ["/usr/sbin/sshd", "-D"]
